name: pineaple_endpoints_location
description: A module for configure the servers endpoints

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0-SNAPSHOT.20220000

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.1
  clean_core: ^1.3.3-RELEASE.20220407

  cupertino_icons: ^1.0.2

  #DB
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  flat_buffers: ^2.0.5
  path_provider: ^2.0.9
  clean_repo_objectbox: ^1.0.0-RELEASE.20220407

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #DB code generation
  build_runner: ^2.1.8
  objectbox_generator: ^1.4.1

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

flutter:

  uses-material-design: true

